### ISSUE TITLE
Hi when would you release diffusionperspective

### ISSUE THREAD

**Issue by YacratesWyh** [rishiu/website#1]
I'm interested in diffusion perspective issues and wondering any more works further into object pasting etc. Looking forward to your release and transcript into comfyui custom code.

**Comment by rishiu** [comment]
Hi @YacratesWyh thanks for the interest! The diffusion perspective code has been released here: https://github.com/rishiu/perspective-enhanced-diffusion. 

I am interested in adding this to ComfyUI but am not sure how -- any guidance would be appreciated.
